# Generated by Django 4.2.11 on 2025-03-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0008_promocode_alter_order_customer_email_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="promocode",
            options={"verbose_name": "Промо код", "verbose_name_plural": "Промо коды"},
        ),
        migrations.AlterField(
            model_name="promocode",
            name="code",
            field=models.CharField(
                max_length=25, unique=True, verbose_name="Промо-код"
            ),
        ),
    ]
