# Generated by Django 4.2.11 on 2025-07-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0009_alter_promocode_options_alter_promocode_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="promocode",
            name="is_percent",
            field=models.BooleanField(
                default=False, verbose_name="Скидка указана в процентах"
            ),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="value",
            field=models.DecimalField(
                decimal_places=2, max_digits=7, verbose_name="Значение скидки"
            ),
        ),
    ]
