# Generated by Django 4.2.4 on 2023-08-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_order_cash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='receiver_name',
            field=models.CharField(blank=True, default='Заказчик является получаетелем', max_length=200, null=True, verbose_name='Имя получателя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='receiver_phone_number',
            field=models.CharField(blank=True, default='Заказчик является получаетелем', max_length=12, null=True, verbose_name='Номер телефона получателя'),
        ),
    ]
