repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
        language_version: python3

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        args: [ --skip-string-normalization, --line-length=100, backend/core/src ]
        language_version: python3

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        args: [ --skip-string-normalization, --line-length=100, backend/tg_bot/src ]
        language_version: python3

  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [ --profile=black ]

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.0.1
    hooks:
      - id: add-trailing-comma

  - repo: https://github.com/pycqa/flake8.git
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [--config, backend/core/.flake8]
        additional_dependencies: [
          "flake8-bugbear",
          "flake8-builtins",
          "flake8-cognitive-complexity",
          "flake8-commas",
          "flake8-quotes",
          "flake8-todo",
          "flake8-variables-names",
        ]

  - repo: https://github.com/pycqa/flake8.git
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [ --config, backend/tg_bot/.flake8 ]
        additional_dependencies: [
          "flake8-bugbear",
          "flake8-builtins",
          "flake8-cognitive-complexity",
          "flake8-commas",
          "flake8-quotes",
          "flake8-todo",
          "flake8-variables-names",
        ]
