# Generated by Django 4.2.4 on 2023-08-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0003_alter_product_options_product_important'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={
                'ordering': ['-important', '-id'],
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='important',
            field=models.IntegerField(default=1, verbose_name='Важность'),
        ),
    ]
