# Generated by Django 4.1.10 on 2023-07-17 18:56

import django.db.models.deletion
from django.db import migrations, models

import products.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('image', models.ImageField(upload_to='images/', verbose_name='Изображение')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
            bases=(products.models.PhotoMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                (
                    'slug',
                    models.SlugField(max_length=128, unique=True, verbose_name='URL параметр'),
                ),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Изображение')),
                ('price', models.IntegerField(verbose_name='Цена')),
                (
                    'type',
                    models.CharField(
                        blank=True,
                        choices=[('bouquet', 'Букет'), ('box', 'Коробка'), ('basket', 'Корзинка')],
                        db_index=True,
                        max_length=7,
                        null=True,
                        verbose_name='Тип товара',
                    ),
                ),
                ('is_active', models.BooleanField(default=True, verbose_name='В продаже')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
            bases=(products.models.PhotoMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('image', models.ImageField(upload_to='images/', verbose_name='Изображение')),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='images',
                        to='products.product',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Дополнительное изоражение',
                'verbose_name_plural': 'Дополнительные изоражения',
            },
            bases=(products.models.PhotoMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'category',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='products.category',
                        verbose_name='Категория',
                    ),
                ),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='products.product',
                        verbose_name='Товар',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Категория товара',
                'verbose_name_plural': 'Категории товаров',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(
                related_name='products',
                through='products.ProductCategory',
                to='products.category',
            ),
        ),
    ]
