# Generated by Django 4.2.4 on 2023-08-28 22:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_alter_product_options_category_important"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["-important", "-id"],
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
    ]
