# Generated by Django 4.2.3 on 2023-07-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.CharField(
                blank=True,
                default='Без примечания',
                max_length=300,
                null=True,
                verbose_name='Примечание',
            ),
        ),
    ]
