# Generated by Django 4.2.5 on 2023-10-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_alter_category_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name="Цена"),
        ),
    ]
