server {
    listen 80;
    listen [::]:80;

    server_name xn----ctbhc5brm3a2c.xn--p1ai
                www.xn----ctbhc5brm3a2c.xn--p1ai
                crocus-rnd.ru
                www.crocus-rnd.ru;

    location ~ /.well-known/acme-challenge {
        allow all;
        root /home/user/market/frontend/build/static/;
    }

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name xn----ctbhc5brm3a2c.xn--p1ai
                www.xn----ctbhc5brm3a2c.xn--p1ai
                crocus-rnd.ru
                www.crocus-rnd.ru;

    ssl_certificate /etc/letsencrypt/live/crocus-rnd.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/crocus-rnd.ru/privkey.pem;

    client_max_body_size 20M;

    location /static/ {
        alias /home/user/market/frontend/build/static/;
    }

    location /media/ {
        alias /home/user/market/backend/core/src/media/;
    }

    location ~ /(api|secretadminpanel) {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-NginX-Proxy true;
        proxy_set_header Upgrade $http_upgrade;

        proxy_pass_header Set-Cookie;
        proxy_pass http://unix:/run/gunicorn.sock;
    }

    location / {
        root /home/user/market/frontend/build/;
        index index.html index.htm;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        try_files $uri $uri/ /index.html;
    }
}
