# Generated by Django 4.2.4 on 2023-08-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_authuser_options_alter_account_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким номером телефона уже существует'}, max_length=12, unique=True, verbose_name='Телефон'),
        ),
    ]
