# Generated by Django 4.1.10 on 2023-07-17 18:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'phone_number',
                    models.CharField(
                        error_messages={
                            'unique': 'Пользователь с таким номером телефона уже существует',
                        },
                        max_length=12,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message='Номер должен начинаться с +7 и состоять из 11 цифр',
                                regex='^+7\\d{10}$',
                            ),
                        ],
                        verbose_name='Телефон',
                    ),
                ),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Аккаунт',
                'verbose_name_plural': 'Аккаунты',
            },
        ),
    ]
